#!/bin/sh
#
MKDIR="/bin/mkdir -p"
SH="/bin/sh"
RM="/bin/rm -f"
CURL="/bin/curl"
MV="/bin/mv"
SYMLNK="/bin/ln -sf"
#

# make the directory to install the dein... maybe not necessary?
${MKDIR} "${HOME}/.cache/dein"
${RM} "${HOME}/.vimrc"

# do not run the shell script directly without downloading first.
# sh -c $(curl -fsSL https://raw.githubusercontent.com/Shougo/dein-installer.vim/master/installer.sh)"
${CURL} -fsSL https://raw.githubusercontent.com/Shougo/dein-installer.vim/master/installer.sh > "${HOME}/installer.sh"

# run the script and feed the number.
# 1. install the $HOME/.cache/dein
# 2. make the .vimrc on $HOME whether not yet exists
${SH} "${HOME}/installer.sh" <<EOF
1
1
EOF

# cleanup
${RM} "${HOME}/installer.sh"

# move it to ~/.dots/vim/pre-bundle.vim, its .vimrc which is automatically generated by the dein 
echo "" >> "${HOME}/.vimrc"
echo "let g:dein_base = s:dein_base" >> "${HOME}/.vimrc"
echo "" >> "${HOME}/.vimrc"
${MV} "${HOME}/.vimrc" "${HOME}/.dots/vim/pre-bundles.vim"

# link the login shell script on the home directory after removing its original
${RM} "${HOME}/.profile"
${RM} "${HOME}/.bashrc"
${RM} "${HOME}/.bash_aliases"
${SYMLNK} "${HOME}/.dots/bash/profile" "${HOME}/.profile"
${SYMLNK} "${HOME}/.dots/bash/bashrc" "${HOME}/.bashrc"
${SYMLNK} "${HOME}/.dots/bash/bash_aliases" "${HOME}/.bash_aliases"

# link the git configuration on the home directory after removing its original
${RM} "${HOME}/.gitconfig"
${SYMLNK} "${HOME}/.dots/gitconfig" "${HOME}/.gitconfig"

# link the '.vimrc' on the home directory after removing its original
${RM} "${HOME}/.vimrc"
${SYMLNK} "${HOME}/.dots/vimrc" "${HOME}/.vimrc"
${RM} "${HOME}/.gvimrc"
${SYMLNK} "${HOME}/.dots/gvimrc" "${HOME}/.gvimrc"

# link the screen configuration on the home directory after removing its original
#${RM} "${HOME}/.screenrc"
#${SYMLNK} "${HOME}/.dots/screenrc" "${HOME}/.screenrc"

# link the tig configuration on the home directory after removing its original
${RM} "${HOME}/.tigrc"
${SYMLNK} "${HOME}/.dots/tigrc" "${HOME}/.tigrc"

# link the uim-fep configuration on the home directory after removing its original
export FEP="uim-fep"
if command -v "${FEP}" ; then
  ${RM} "${HOME}/.uim"
else
  sudo apt install uim uim-mozc -y >/dev/null 2>&1
fi
${SYMLNK} "${HOME}/.dots/uim" "${HOME}/.uim"

# creates the default directories, apps, libs, projs and workspace
${MKDIR} ${HOME}/apps ${HOME}/libs ${HOME}/projs ${HOME}/workspace

# use terminal configuration
cat <<EOF > ${HOME}/.dots/terminalrc
#
#
export TERMINAL=
EOF

